// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://maszvvwzfteyjqllxkvk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hc3p2dnd6ZnRleWpxbGx4a3ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3ODY5OTcsImV4cCI6MjA2MDM2Mjk5N30.RVmE_Tlgb_gNku0TNizzo73pcr-9P1F0M5bCnlpotIc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);